# Generated by Django 5.1.5 on 2025-01-24 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_managers_remove_user_created_at_and_more'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('is_recipient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.recipient')),
            ],
        ),
    ]
