# Generated by Django 5.1.5 on 2025-01-27 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_alter_user_managers_remove_user_created_at_and_more"),
        ("location", "0004_alter_donorlocation_donor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donorlocation",
            name="donor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="donor_location",
                to="authentication.donor",
            ),
        ),
    ]
