# Generated by Django 5.1.5 on 2025-01-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('donor', 'donor'), ('user', 'user')], default='user', max_length=10),
        ),
    ]
