# Generated by Django 5.1.5 on 2025-01-27 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_alter_user_managers_remove_user_created_at_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OTPVerification",
        ),
    ]
