# Generated by Django 5.1.5 on 2025-01-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_delete_otpverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipient",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
