# Generated by Django 5.1.5 on 2025-01-29 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_alter_user_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipient",
            name="email",
        ),
    ]
